name: Actualizacion Automatizada MEF

on:
  schedule:
    - cron: '0 */6 * * *' # Cada 6 horas
  workflow_dispatch: # Permite darle al botón "Run" manualmente si

permissions:
  contents: write

jobs:
  extract_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ... dentro de los pasos de tu workflow
      - name: Ejecutar recolección
        run: |
          python ranking.py # Ejecuta el nuevo script del ranking
      # ... dentro de los pasos de tu workflow

      - name: Guardar cambios
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data_ranking.json
          # El commit incluye la fecha para que el historial sea claro
          git commit -m "📊 Datos Reales MEF Actualizados: $(date)" || echo "Sin cambios para commitear"
          git push origin main

      
